export const GET_SOURCES = "GET_SOURCES";
export const GET_SOURCES_SUCCESS = "GET_SOURCES_SUCCESS";
export const MARK_FAVORITE_SOURCE = "MARK_FAVORITE_SOURCE";
export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_OFF = "SET_LOADING_OFF";